kind: pipeline
type: docker
name: default

steps:
  - name: maven_package
    image: maven:3.6.3-jdk-11
    commands:
      - find $HOME/.m2/repository -name '*.lastUpdated' | xargs rm -rf
      - mvn clean package -DskipTests -U
    volumes:
      - name: drone_home
        path: /root

  - name: docker_run
    image: docker:stable-dind
    commands:
      - docker ps | grep mm-server:v1 | awk '{docker container stop $1}'
      - docker ps -a | grep mm-server:v1 | awk '{docker container rm $1}'
      - docker build -t mm-server:v1 .
      - docker run -dit -p 8080:8080 -v /home/ubunt/mm-server/upload:/upload --name mm-server mm-server:v1
      - docker ps -a | grep mm-server:v1

volumes:
  - name: drone_home
    host:
      path: /home/ubuntu/data/drone/home

trigger:
  branch:
    - master
  event:
    - push

