kind: pipeline
type: docker
name: default

steps:
  - name: maven_package
    image: maven:3.6.3-jdk-11
    privileged: true
    commands:
      - mvn clean package -DskipTests -U
    volumes:
      - name: drone_maven_repository
        path: /root/.m2/repository

  - name: docker_run
    image: docker:stable-dind
    privileged: true
    commands:
      - if [ $(docker ps -a | grep 'mm-server' | awk '{print $1}') ]; then docker rm -f mm-server; fi
      - if [ $(docker images | grep 'mm-server:v1' | awk '{print $3}') ]; then docker rmi mm-server:v1; fi
      - docker build -t mm-server:v1 .
      - docker run -dit -p 8080:8080 -v /mm-server/upload:/upload --name mm-server mm-server:v1
      - docker ps -a | grep mm-server:v1
    volumes:
      - name: docker
        path: /var/run/docker.sock
      - name: mm_server_upload
        path: /mm-server/upload

volumes:
  - name: drone_maven_repository
    host:
      path: /home/ubuntu/drone-maven-repository
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: mm_server_upload
    host:
      path: /home/ubuntu/mm-server/upload

trigger:
  branch:
    - master
  event:
    - push

