spring:
  datasource:
    url: jdbc:mysql://172.30.0.5:3306/mm?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mm-config:
  # 文件上传的路径
  file-upload-folder: file:/upload/
  # 上传文件的资源访问路径
  file-upload-access-path: /upload/**
  # 访问上传资源的前缀
  file-http-prefix: http://94.191.66.92/:8080/upload/
  # rsa公钥
  rsa-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCAVWBbicHAiQ4Z7ktCm8Ui4fqbGhKfw9ZKbkhtR7VeugGO9Bo9Z31KCwefrLoD/iIO29sAVn973u1KXil93B01Wd3zK5kNiGb+I3ubB1QzGivnpGPjbLGaeruau6aG7WtaO861KSo7U0AvBAfG3ZmqrsT63HOCjJMc2TdxlIBEOwIDAQAB
  # rsa私钥
  rsa-private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIBVYFuJwcCJDhnuS0KbxSLh+psaEp/D1kpuSG1HtV66AY70Gj1nfUoLB5+sugP+Ig7b2wBWf3ve7UpeKX3cHTVZ3fMrmQ2IZv4je5sHVDMaK+ekY+NssZp6u5q7pobta1o7zrUpKjtTQC8EB8bdmaquxPrcc4KMkxzZN3GUgEQ7AgMBAAECgYAYa6atZJZpA+uaBZ1urGOkEqp0j06R9ls1yKyhlu6teunHAS5pFuNhjp3BxcWT8u0aNL4E33Dc6nvvFeIBYDxyYGnM/k4GVmiiM3aEphjxYHIv4xWwq1nAgYRIHWArFUnBooefSysw0FjNFbBymrv2VS820+jHb5LNmyI7b/57wQJBAMFiY9QMBifHxO5+YrEJreFFNquFU1nI92UIWhklRiB37/ylnZA7l7SgvCy8tFt9OLlfeNYJ5E8/TKDXJOYKOFsCQQCp4u2/EkKsPw8/HXI2W8Y+7Lg2e0FUPVECguBeBNinksXGBY//BtIvjkdVOCPJ7PagJ5Nozz5JRQJe2SeK2OmhAkEAg6I3laVBo15l/HlnMF8ITujQF9y/KcSUMd+HhMpMe9loMC+DmyQVVcx7inBAzG3maLhGBlvhXtgVjv4jjbqzNQJAZR63BtE2sFIEoDvFvMdZtCCw8XTiCONKceU26Z+W2f/KCrlK4bDMsRPOL9JvswSCNAf6fRtGZtRVueEl4UaFoQJARZsnP5aHyTbOefvBqbLb55SMM86GZaZwxmXp8ygJRJ04skUAAQw8+6BDPm0ruKIpbpJsbL2Nq3vizEmkC+avMA==
  # 用户默认密码
  user-default-pwd: 123456