spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format-sql: true
      open-in-view: false
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=500,expireAfterAccess=30s
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # 邮件发送配置
  mail:
    host: smtp.163.com
    username: mhliso@163.com
    password: mhliso8888cn